function interceptCDMSummaryRequest({ request, params }) {
    return fetch(request).then((response) => {
      if (!response.ok) {
        throw Error('Error occured with response status ' + response.status);
      }
      self.console.log(response, 'from cdm summary service worker');
      return response;
    }).catch((error) => {
      const response = {
        "result": [
          {
            "person_id": 849398,
            "encounter_id": 8369018,
            "encounter_type": "CDMDispensary",
            "encounter_type_description": "Chronic Disease Management (CDM) Dispensary Form",
            "encounter_datetime": "2019-02-13T08:40:47.000Z",
            "is_clinical_encounter": 1,
            "rtc_date": "2019-03-12T21:00:00.000Z",
            "prev_encounter_datetime_cdm": "2019-02-04T21:00:00.000Z",
            "prev_clinical_datetime_cdm": "2018-09-25T11:09:01.000Z",
            "prev_encounter_type_cdm": 99999,
            "next_encounter_datetime_cdm": "2019-02-24T21:00:00.000Z",
            "death_date": null,
            "sbp": null,
            "dbp": null,
            "rbs": null,
            "fbs": null,
            "hb_a1c": null,
            "hb_a1c_date": null,
            "dm_status": null,
            "htn_status": null,
            "dm_meds": null,
            "htn_meds": null,
            "lmp": null,
            "pulse": null,
            "creatinine": null,
            "creatinine_date": null,
            "total_cholesterol": null,
            "ldl": null,
            "triglycerides": null,
            "lipid_panel_date": null,
            "problems": null,
            "prescriptions": null,
            "dm_meds_name": "",
            "htn_meds_name": "",
            "problems_name": "",
            "dm_status_name": "",
            "htn_status_name": ""
          },
          {
            "person_id": 849398,
            "encounter_id": 8010333,
            "encounter_type": "CDMDispensary",
            "encounter_type_description": "Chronic Disease Management (CDM) Dispensary Form",
            "encounter_datetime": "2018-09-25T11:09:01.000Z",
            "is_clinical_encounter": 1,
            "rtc_date": "2018-09-26T21:00:00.000Z",
            "prev_encounter_datetime_cdm": "2018-09-25T10:40:44.000Z",
            "prev_clinical_datetime_cdm": "2018-09-25T10:40:44.000Z",
            "prev_encounter_type_cdm": 96,
            "next_encounter_datetime_cdm": "2018-09-25T10:40:44.000Z",
            "death_date": null,
            "sbp": null,
            "dbp": null,
            "rbs": null,
            "fbs": null,
            "hb_a1c": null,
            "hb_a1c_date": null,
            "dm_status": null,
            "htn_status": null,
            "dm_meds": null,
            "htn_meds": null,
            "lmp": null,
            "pulse": null,
            "creatinine": null,
            "creatinine_date": null,
            "total_cholesterol": null,
            "ldl": null,
            "triglycerides": null,
            "lipid_panel_date": null,
            "problems": null,
            "prescriptions": null,
            "dm_meds_name": "",
            "htn_meds_name": "",
            "problems_name": "",
            "dm_status_name": "",
            "htn_status_name": ""
          },
          {
            "person_id": 849398,
            "encounter_id": 8010258,
            "encounter_type": "CDMDispensary",
            "encounter_type_description": "Chronic Disease Management (CDM) Dispensary Form",
            "encounter_datetime": "2018-09-25T10:40:44.000Z",
            "is_clinical_encounter": 1,
            "rtc_date": "2018-09-26T21:00:00.000Z",
            "prev_encounter_datetime_cdm": "2018-09-25T10:27:41.000Z",
            "prev_clinical_datetime_cdm": "2018-09-25T10:27:41.000Z",
            "prev_encounter_type_cdm": 96,
            "next_encounter_datetime_cdm": "2018-09-25T10:27:41.000Z",
            "death_date": null,
            "sbp": null,
            "dbp": null,
            "rbs": null,
            "fbs": null,
            "hb_a1c": null,
            "hb_a1c_date": null,
            "dm_status": null,
            "htn_status": null,
            "dm_meds": null,
            "htn_meds": null,
            "lmp": null,
            "pulse": null,
            "creatinine": null,
            "creatinine_date": null,
            "total_cholesterol": null,
            "ldl": null,
            "triglycerides": null,
            "lipid_panel_date": null,
            "problems": null,
            "prescriptions": null,
            "dm_meds_name": "",
            "htn_meds_name": "",
            "problems_name": "",
            "dm_status_name": "",
            "htn_status_name": ""
          },
          {
            "person_id": 849398,
            "encounter_id": 8010222,
            "encounter_type": "CDMDispensary",
            "encounter_type_description": "Chronic Disease Management (CDM) Dispensary Form",
            "encounter_datetime": "2018-09-25T10:27:41.000Z",
            "is_clinical_encounter": 1,
            "rtc_date": "2018-09-26T21:00:00.000Z",
            "prev_encounter_datetime_cdm": "2018-07-31T21:00:00.000Z",
            "prev_clinical_datetime_cdm": null,
            "prev_encounter_type_cdm": 99999,
            "next_encounter_datetime_cdm": "2018-10-18T21:00:00.000Z",
            "death_date": null,
            "sbp": null,
            "dbp": null,
            "rbs": null,
            "fbs": null,
            "hb_a1c": null,
            "hb_a1c_date": null,
            "dm_status": null,
            "htn_status": null,
            "dm_meds": null,
            "htn_meds": null,
            "lmp": null,
            "pulse": null,
            "creatinine": null,
            "creatinine_date": null,
            "total_cholesterol": null,
            "ldl": null,
            "triglycerides": null,
            "lipid_panel_date": null,
            "problems": null,
            "prescriptions": null,
            "dm_meds_name": "",
            "htn_meds_name": "",
            "problems_name": "",
            "dm_status_name": "",
            "htn_status_name": ""
          }
        ]
      };
      return new Response(JSON.stringify(response), { status: 200 });
    });
  }
  