dist: xenial
language: node_js
node_js:
- "10"
services:
- docker
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
  # Updating NPM to relevant version >= 3 on Node.JS LTS
- npm i -g brfs
script:
- npm run lint
- npm run build-prod
#- npm run test
sudo: required
addons:
  apt:
    packages:
    - sshpass
    - google-chrome-stable
deploy:
  provider: s3
  access_key_id: "$DIGITAL_OCEAN_SPACES_KEY_ID"
  secret_access_key: "$DIGITAL_OCEAN_SPACES_ACCESS_KEY"
  bucket: "$DIGITAL_OCEAN_SPACES_BUCKET"
  endpoint: "$DIGITAL_OCEAN_SPACES_ENDPOINT"
  cache-control: "max-age=31536000"
  local_dir: $TRAVIS_BRANCH
  skip_cleanup: true
  acl: public_read
  on:
    all_branches: true
after_success:
- mv dist/ngx-amrs $TRAVIS_BRANCH
